runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

libraries:
- name: ssl
  version: latest
- name: pycrypto
  version: "2.6"
  
builtins:  
- remote_api: on